### ISSUE TITLE
Advantages over zc/yg.lockfile?

### ISSUE THREAD

**Issue by pombredanne** [mwilliamson/locket.py#9]
Hi:
I am always on the lookout for a better cross-process file lock that works flawlessly at scale (e.g. think across 1000+ processes on a 144CPU machine) and on Linux, macOS and Windows.

I am using zg/yg/lockfile here https://github.com/nexB/scancode-toolkit/blob/4e63a6775a895fdec5a3a53f96013399fa34b1b7/src/licensedcode/cache.py#L122 

What would be the plus of locket?

**Comment by mwilliamson** [comment]
I know nothing about zc/yg.lockfile, so I'm afraid I have no idea.

**Comment by pombredanne** [comment]
Thank for the quick feedback!

**Comment by pombredanne** [comment]
FWIW, https://pypi.python.org/pypi/zc.lockfile and https://pypi.python.org/pypi/yg.lockfile/
